# Cash Flow Management Service Configuration
spring:
  application:
    name: cash-flow-management-service
  
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=cashflow_db;encrypt=true;trustServerCertificate=true
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:YourStrong@Passw0rd}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: true
  
  liquibase:
    enabled: false
  
  webflux:
    webclient:
      max-in-memory-size: 10MB

server:
  port: 8080

logging:
  level:
    com.financial.cashflow: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

cashflow:
  calculation:
    max-contracts-per-request: 1000
    max-date-range-days: 1825  # 5 years
    timeout-seconds: 300
  market-data:
    cache-ttl-hours: 24
    max-cache-size-mb: 1000
    external-timeout-seconds: 10
  archival:
    retention-months: 84  # 7 years
    archival-frequency: MONTHLY
