global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Cash Flow Management Service
  - job_name: 'cash-flow-service'
    static_configs:
      - targets: ['cash-flow-service:8080']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s
    scrape_timeout: 5s

  # SQL Server (if using SQL Server Exporter)
  - job_name: 'sqlserver'
    static_configs:
      - targets: ['sqlserver:1433']
    scrape_interval: 30s

  # Redis (if using Redis Exporter)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s

  # Kafka (if using Kafka Exporter)
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9092']
    scrape_interval: 30s
